spring.application.name=cliente-service
server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.datasource.url=jdbc:postgresql://ep-mute-mountain-aca291be-pooler.sa-east-1.aws.neon.tech/banco_clientes?user=neondb_owner&password=npg_nmLi9c1fUraq&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=sua_senha_aqui

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect